name: ci

on:
  push:
  pull_request:

jobs:
  windows-build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        shell: pwsh
        run: cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release

      - name: Build
        shell: pwsh
        run: cmake --build build

      - name: Test
        shell: pwsh
        run: ctest --test-dir build --output-on-failure